services:
  trankit-fnbr:
    build:
      context: .
    container_name: fnbr-trankit
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8405:80"
    volumes:
      - ./cache:/code/cache
